import { useState } from "react";
import { Button, Input, Select, Textarea } from "@ccgui/plugin-ui";
import type { DiscoveredModel, ModelDiscoveryResult } from "@ccgui/plugin-sdk";
import { compatible, engines, id, policyKeys, type Binding, type PolicyOverrides, type RegistryView } from "./registry";
import { PolicyEditor, type UpdateDraft } from "./fields";
import type { ProviderController } from "./controller";
import { enginePolicies } from "./projection";

export function BindingEditor({ binding, draft, update, controller, replaceDraft }: { binding: Binding; draft: RegistryView; update: UpdateDraft; controller: ProviderController; replaceDraft: (draft: RegistryView, expected: RegistryView) => void }) {
  const [templates, setTemplates] = useState<DiscoveredModel[]>(controller.templatesFor(binding));
  const [templateIndex, setTemplateIndex] = useState("");
  const [modelId, setModelId] = useState("");
  const [keyId, setKeyId] = useState("");
  const [discovery, setDiscovery] = useState<ModelDiscoveryResult | null>(null);
  const [checked, setChecked] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const endpoint = draft.endpoints.find((e) => e.id === binding.endpointId);
  const template = templates[Number(templateIndex)];
  const models = draft.models.filter((m) => m.providerId === binding.providerId);
  const mappings = draft.mappings.filter((m) => m.bindingId === binding.id);
  async function perform(action: () => Promise<void>, message: string) { setBusy(true); setError(""); try { await action(); } catch { setError(message); } finally { setBusy(false); } }
  return <fieldset className="up-card" disabled={busy}><legend>{binding.engineId} · {endpoint?.name ?? "Choose endpoint"}</legend>
    <div className="up-grid"><label className="up-check"><input type="checkbox" checked={binding.enabled} onChange={(event) => update((r) => { r.bindings.find((b) => b.id === binding.id)!.enabled = event.target.checked; })} />Enabled</label>
      <label>Endpoint<Select value={binding.endpointId} onChange={(event) => update((r) => { const b = r.bindings.find((b) => b.id === binding.id)!; b.endpointId = event.target.value; delete b.targetGrantId; })}>{draft.endpoints.filter((e) => e.providerId === binding.providerId).map((e) => <option value={e.id} key={e.id}>{e.name} · {e.protocol}</option>)}</Select></label>
      <label>Binding default Key<Select value={binding.credential.kind === "explicit" ? binding.credential.credentialId : ""} onChange={(event) => update((r) => { r.bindings.find((b) => b.id === binding.id)!.credential = event.target.value ? { kind: "explicit", credentialId: event.target.value } : { kind: "inherit" }; })}><option value="">Inherit Provider default on explicit bind</option>{draft.credentials.filter((c) => c.providerId === binding.providerId && c.enabled).map((c) => <option key={c.id} value={c.id}>{c.name} · {c.remark ?? "No note"}</option>)}</Select></label>
      <label>Suggested model · first when explicitly choosing this Provider<Select value={binding.defaultModelId ?? ""} onChange={(event) => update((r) => { r.bindings.find((b) => b.id === binding.id)!.defaultModelId = event.target.value || undefined; })}><option value="">No suggestion</option>{models.filter((m) => mappings.some((mapping) => mapping.providerModelId === m.id && mapping.enabled)).map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</Select></label>
      <label>Execution environment<Select value={binding.executionTarget.kind} onChange={(event) => { setTemplates([]); setTemplateIndex(""); update((r) => { const b = r.bindings.find((b) => b.id === binding.id)!; b.executionTarget = event.target.value === "local" ? { kind: "local" } : { kind: "wsl", hostId: "", distro: "" }; delete b.targetGrantId; }); }}><option value="local">Local</option><option value="wsl">WSL · separately authorized</option></Select></label>
      {binding.executionTarget.kind === "wsl" && <><label>WSL host ID<Input value={binding.executionTarget.hostId} onChange={(event) => update((r) => { const b = r.bindings.find((b) => b.id === binding.id)!; if (b.executionTarget.kind === "wsl") b.executionTarget.hostId = event.target.value; delete b.targetGrantId; })} /></label><label>WSL distribution<Input value={binding.executionTarget.distro} onChange={(event) => update((r) => { const b = r.bindings.find((b) => b.id === binding.id)!; if (b.executionTarget.kind === "wsl") b.executionTarget.distro = event.target.value; delete b.targetGrantId; })} /></label></>}
    </div>
    {endpoint && !compatible(binding.engineId, endpoint.protocol) && <p role="alert" className="up-error">This CLI cannot consume {endpoint.protocol}. Keep native models, or choose a compatible endpoint. No protocol proxy is provided.</p>}
    {enginePolicies[binding.engineId] && <p className="up-muted">CLI token policy: explicitly clear unsupported fields ({enginePolicies[binding.engineId].unsupported.join(", ") || "none"}); known values required for {enginePolicies[binding.engineId].required.join(", ") || "none"}. Unknown values are never fabricated.</p>}
    <p className="up-muted">Target authorization: {binding.targetGrantId ? "Granted for the recorded URL / environment / Key revisions" : "Required before publishing"}. Changing Key values requires a new grant.</p>
    <div className="up-toolbar"><Button disabled={busy} onClick={() => void perform(async () => { replaceDraft(await controller.authorizeDraft(draft, binding.id), draft); }, "Target authorization was not granted. Nothing was sent to the endpoint.")}>Authorize this exact target</Button><Button disabled={busy} onClick={() => void perform(async () => { setTemplates(await controller.loadTemplates(binding, true)); setTemplateIndex(""); }, "Official templates could not be loaded for this CLI/environment. Existing mappings were preserved.")}>Refresh official templates</Button></div>
    <details><summary>CLI options · explicit, non-sensitive only</summary><div className="up-grid">
      <label>Service tier<Select value={binding.options.serviceTier ?? ""} onChange={(event) => update((r) => { const options = r.bindings.find((b) => b.id === binding.id)!.options; if (event.target.value) options.serviceTier = event.target.value as "default" | "priority"; else delete options.serviceTier; })}><option value="">Not injected</option><option value="default">Default</option><option value="priority">Priority</option></Select></label>
      <label>Always thinking<Select value={binding.options.alwaysThinkingEnabled === undefined ? "" : String(binding.options.alwaysThinkingEnabled)} onChange={(event) => update((r) => { const options = r.bindings.find((b) => b.id === binding.id)!.options; if (event.target.value) options.alwaysThinkingEnabled = event.target.value === "true"; else delete options.alwaysThinkingEnabled; })}><option value="">Not injected</option><option value="true">Enabled</option><option value="false">Disabled</option></Select></label>
      <label>Non-sensitive headers · one Name: value per line<Textarea value={Object.entries(binding.options.headers ?? {}).map(([name, value]) => `${name}: ${value}`).join("\n")} onChange={(event) => update((r) => { const headers: Record<string, string> = {}; for (const line of event.target.value.split("\n").filter(Boolean)) { const colon = line.indexOf(":"); headers[colon < 0 ? line : line.slice(0, colon).trim()] = colon < 0 ? "" : line.slice(colon + 1).trim(); } r.bindings.find((b) => b.id === binding.id)!.options.headers = headers; })} /></label></div></details>
    <h4>Official-template model mappings</h4><p className="up-muted">Choose a template, then map a logical model. Changing a template is explicit; no template defaults are copied into registry.json.</p>
    <div className="up-grid"><label>Official template<Select value={templateIndex} onChange={(event) => setTemplateIndex(event.target.value)}><option value="">Choose a template</option>{templates.map((t, index) => <option key={`${t.modelId}:${t.templateRef?.revision}`} value={index}>{t.label ?? t.modelId} · {t.templateRef?.revision.slice(0, 8)}</option>)}</Select></label>
    <label>Unmapped Provider model<Select value={modelId} onChange={(event) => setModelId(event.target.value)}><option value="">Choose a model</option>{models.filter((m) => !mappings.some((mapping) => mapping.providerModelId === m.id)).map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</Select></label></div>
    <Button size="sm" disabled={!modelId || templateIndex === "" || !template?.templateRef} onClick={() => { update((r) => { r.mappings.push({ id: id(), bindingId: binding.id, providerModelId: modelId, templateRef: template!.templateRef!, selector: { kind: "wire" }, policy: {}, enabled: true }); }); setModelId(""); }}>Add mapping to draft</Button>
    {mappings.map((mapping) => { const model = models.find((m) => m.id === mapping.providerModelId)!; const activeTemplate = templates.find((t) => t.templateRef?.modelId === mapping.templateRef.modelId && t.templateRef?.revision === mapping.templateRef.revision); return <fieldset className="up-card" key={mapping.id}><legend>{model.name} → {model.wireIds[binding.endpointId] ?? "Missing wire ID"}</legend>
      <label className="up-check"><input type="checkbox" checked={mapping.enabled} onChange={(event) => update((r) => { r.mappings.find((m) => m.id === mapping.id)!.enabled = event.target.checked; const b = r.bindings.find((b) => b.id === binding.id)!; if (!event.target.checked && b.defaultModelId === mapping.providerModelId) delete b.defaultModelId; })} />Visible in model picker</label>
      <p className="up-muted">Template {mapping.templateRef.modelId} · revision {mapping.templateRef.revision.slice(0, 12)}{!activeTemplate && " · refresh and explicitly choose a replacement if unavailable"}</p>
      <Button size="sm" disabled={templateIndex === "" || !template?.templateRef} onClick={() => update((r) => { r.mappings.find((m) => m.id === mapping.id)!.templateRef = template!.templateRef!; })}>Use selected official template</Button>
      <div className="up-grid"><label>Selector<Select value={mapping.selector.kind} onChange={(event) => update((r) => { r.mappings.find((m) => m.id === mapping.id)!.selector = event.target.value === "wire" ? { kind: "wire" } : { kind: "alias", alias: "" }; })}><option value="wire">Wire model ID</option><option value="alias">Independent CLI alias</option></Select></label>
      {mapping.selector.kind === "alias" && <label>Alias<Input value={mapping.selector.alias} onChange={(event) => update((r) => { r.mappings.find((m) => m.id === mapping.id)!.selector = { kind: "alias", alias: event.target.value }; })} /></label>}</div>
      <PolicyEditor scope="CLI mapping override" value={mapping.policy} shared={model.sharedPolicy} official={activeTemplate?.tokenPolicy} onChange={(value) => update((r) => { r.mappings.find((m) => m.id === mapping.id)!.policy = value; })} />
      <Button variant="ghost" size="sm" onClick={() => update((r) => { r.mappings = r.mappings.filter((m) => m.id !== mapping.id); })}>Remove mapping from draft</Button>
    </fieldset>; })}
    <details><summary>Discover models from the authorized endpoint</summary><p className="up-muted">Uses the saved/published binding and one selected Key. Candidates stay in memory; failed/partial discovery never deletes maintained models.</p>
      <label>Discovery Key<Select value={keyId} onChange={(event) => setKeyId(event.target.value)}><option value="">Explicitly resolve saved binding default</option>{draft.credentials.filter((c) => c.providerId === binding.providerId && c.enabled).map((c) => <option key={c.id} value={c.id}>{c.name} · {c.remark ?? "No note"}</option>)}</Select></label>
      <Button disabled={busy} onClick={() => void perform(async () => { setDiscovery(await controller.discover(binding.id, keyId || undefined)); setChecked([]); }, "Discovery failed. Check the saved publication, target grant and selected Key. No alternative Key was attempted.")}>Discover candidates</Button>
      {discovery && <><p role="status">Discovery: {discovery.status} · {new Date(discovery.observedAt).toLocaleString()}{discovery.status === "failed" && " · retained previous candidates"}</p>{discovery.models.map((candidate) => <label className="up-check" key={candidate.modelId}><input type="checkbox" checked={checked.includes(candidate.modelId)} onChange={(event) => setChecked(event.target.checked ? [...checked, candidate.modelId] : checked.filter((m) => m !== candidate.modelId))} />{candidate.label ?? candidate.modelId} · {candidate.evidence} · context {candidate.tokenPolicy.contextWindowTokens ?? "unknown"}</label>)}
        <Button disabled={!checked.length || templateIndex === "" || !template?.templateRef || discovery.status === "unsupported"} onClick={() => {
          update((r) => { for (const candidate of discovery.models.filter((c) => checked.includes(c.modelId))) { if (candidate.protocol && endpoint?.protocol !== candidate.protocol) throw new Error("Candidate protocol differs from the binding endpoint"); const modelId = id(); const sharedPolicy: PolicyOverrides = {}; for (const key of policyKeys) if (candidate.tokenPolicy[key] !== undefined) sharedPolicy[key] = { kind: "value", value: candidate.tokenPolicy[key]! }; r.models.push({ id: modelId, providerId: binding.providerId, name: candidate.label ?? candidate.modelId, wireIds: { [binding.endpointId]: candidate.modelId }, sharedPolicy, capabilities: candidate.capabilities }); r.mappings.push({ id: id(), bindingId: binding.id, providerModelId: modelId, templateRef: template!.templateRef!, selector: { kind: "wire" }, policy: {}, enabled: true }); } }); setChecked([]);
        }}>Add selected candidates and map to selected template</Button></>}
    </details>
    {error && <p role="alert" className="up-error">{error}</p>}
    <Button variant="ghost" size="sm" disabled={busy} onClick={() => update((r) => { r.bindings = r.bindings.filter((b) => b.id !== binding.id); r.mappings = r.mappings.filter((m) => m.bindingId !== binding.id); })}>Remove CLI binding from draft</Button>
  </fieldset>;
}

export function Bindings({ providerId, draft, update, controller, replaceDraft }: { providerId: string; draft: RegistryView; update: UpdateDraft; controller: ProviderController; replaceDraft: (draft: RegistryView, expected: RegistryView) => void }) {
  const [engine, setEngine] = useState("");
  const endpoint = draft.endpoints.find((e) => e.providerId === providerId);
  return <div className="up-stack"><h3>CLI mappings</h3><div className="up-toolbar"><label>Add CLI binding<Select value={engine} onChange={(event) => setEngine(event.target.value)}><option value="">Choose CLI</option>{engines.filter((engineId) => !draft.bindings.some((b) => b.providerId === providerId && b.engineId === engineId)).map((engineId) => <option key={engineId}>{engineId}</option>)}</Select></label><Button disabled={!engine || !endpoint} onClick={() => { update((r) => { r.bindings.push({ id: id(), providerId, engineId: engine, endpointId: endpoint!.id, enabled: true, credential: { kind: "inherit" }, executionTarget: { kind: "local" }, options: {} }); }); setEngine(""); }}>Add binding</Button></div>
    {!endpoint && <p>Add an endpoint in Details first.</p>}
    <p className="up-muted">DSH, Agy, Qoder and Qoder CN retain their native capabilities. Unsupported Provider/protocol bindings cannot publish.</p>
    {draft.bindings.filter((b) => b.providerId === providerId).map((binding) => <BindingEditor key={binding.id} binding={binding} draft={draft} update={update} controller={controller} replaceDraft={replaceDraft} />)}
  </div>;
}
